// SPDX-License-Identifier: Apache-2.0

package lightning

import (
	"encoding/base64"
	"encoding/hex"
	"strings"
	"testing"

	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/config"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/keystore"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/keystore/mocks"
	"github.com/BitBoxSwiss/bitbox-wallet-app/util/observable"
	"github.com/BitBoxSwiss/bitbox-wallet-app/util/test"
	"github.com/stretchr/testify/require"
)

// Expected credentials derived from the fixed test entropy 0x00..0x0f. Both values must be
// fully deterministic from the entropy so a lost lightning.json can be regenerated by
// re-activating with the same device.
const (
	testMnemonic       = "abandon hotel tank rate various erode alone trust always accident tube split cloud rebel turn true taxi piece prevent devote ivory analyst cabbage garbage"
	testWalletPassword = "2206134f1049b3fd4d49bd97e7000a57c81ff84b72b35cbdbec2bf8cd7b572f0"
)

type testEnvironment struct {
	canEncrypt bool
	keys       map[string]string
	storeErr   error
	loadErr    error
	deleteErr  error
	loadCalls  int
}

func (e *testEnvironment) CanEncryptLightningMnemonic() bool {
	return e.canEncrypt
}

func (e *testEnvironment) StoreLightningEncryptionKey(accountCode string, encryptionKey string) error {
	if e.storeErr != nil {
		return e.storeErr
	}
	if e.keys == nil {
		e.keys = map[string]string{}
	}
	e.keys[accountCode] = encryptionKey
	return nil
}

func (e *testEnvironment) LoadLightningEncryptionKey(accountCode string) (string, error) {
	e.loadCalls++
	if e.loadErr != nil {
		return "", e.loadErr
	}
	return e.keys[accountCode], nil
}

func (e *testEnvironment) DeleteLightningEncryptionKey(accountCode string) error {
	if e.deleteErr != nil {
		return e.deleteErr
	}
	delete(e.keys, accountCode)
	return nil
}

func newTestLightning(t *testing.T, environment environment) *Lightning {
	t.Helper()

	appConfigFilename := test.TstTempFile("appConfig")
	accountsConfigFilename := test.TstTempFile("accountsConfig")
	lightningConfigFilename := test.TstTempFile("lightningConfig")

	cfg, err := config.NewConfig(appConfigFilename, accountsConfigFilename, lightningConfigFilename)
	require.NoError(t, err)

	if environment == nil {
		environment = &testEnvironment{}
	}

	return NewLightning(
		cfg,
		environment,
		func() keystore.Keystore { return nil },
		nil,
		nil,
	)
}

func testKeystore() keystore.Keystore {
	return &mocks.KeystoreMock{
		SupportsDeterministicEntropyFunc: func() bool { return true },
		DeterministicEntropyFunc: func() ([]byte, error) {
			return []byte{
				0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
				0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
			}, nil
		},
		RootFingerprintFunc: func() ([]byte, error) {
			return []byte{0xde, 0xad, 0xbe, 0xef}, nil
		},
	}
}

func TestAccount(t *testing.T) {
	lightning := newTestLightning(t, nil)
	require.Nil(t, lightning.Account())

	require.NoError(t, lightning.backendConfig.ModifyLightningConfig(func(cfg *config.LightningConfig) error {
		cfg.Accounts = []*config.LightningAccountConfig{
			{Code: "v0-first-ln-0", Number: 0},
			{Code: "v0-second-ln-1", Number: 1},
		}
		return nil
	}))

	account := lightning.Account()
	require.NotNil(t, account)
	require.Equal(t, "v0-first-ln-0", string(account.Code))
}

func TestSetAccount(t *testing.T) {
	lightning := newTestLightning(t, nil)

	account := &config.LightningAccountConfig{
		Seed:            "test mnemonic",
		RootFingerprint: []byte{0xde, 0xad, 0xbe, 0xef},
		Code:            "v0-deadbeef-ln-0",
		Number:          0,
	}
	require.NoError(t, lightning.SetAccount(account))

	storedAccount := lightning.Account()
	require.NotNil(t, storedAccount)
	require.NotSame(t, account, storedAccount)
	require.Equal(t, account, storedAccount)
	require.Len(t, lightning.backendConfig.LightningConfig().Accounts, 1)

	account.Code = "mutated"
	require.Equal(t, "v0-deadbeef-ln-0", string(lightning.Account().Code))

	require.NoError(t, lightning.SetAccount(nil))
	require.Nil(t, lightning.Account())
	require.Empty(t, lightning.backendConfig.LightningConfig().Accounts)
}

func TestReady(t *testing.T) {
	lightning := newTestLightning(t, nil)
	require.False(t, lightning.Ready())

	require.NoError(t, lightning.SetAccount(&config.LightningAccountConfig{
		Seed:            "test mnemonic",
		RootFingerprint: []byte{0xde, 0xad, 0xbe, 0xef},
		Code:            "v0-deadbeef-ln-0",
		Number:          0,
	}))
	// No wallet state has been pushed yet.
	require.False(t, lightning.Ready())
	require.Error(t, lightning.CheckActive())

	lightning.SetState(&walletState{Ready: false})
	require.False(t, lightning.Ready())

	lightning.SetState(&walletState{Ready: true})
	require.True(t, lightning.Ready())
	require.NoError(t, lightning.CheckActive())

	require.NoError(t, lightning.SetAccount(nil))
	require.False(t, lightning.Ready())
}

func TestActivateDeterministic(t *testing.T) {
	// Activating twice from scratch with the same device entropy must yield the exact same
	// mnemonic and wallet password.
	for i := 0; i < 2; i++ {
		lightning := newTestLightning(t, nil)
		lightning.getKeystore = testKeystore

		require.NoError(t, lightning.Activate())

		account := lightning.Account()
		require.NotNil(t, account)
		require.Equal(t, "v0-deadbeef-ln-0", string(account.Code))
		// The test environment cannot encrypt, so the secrets are stored in plaintext.
		require.Equal(t, testMnemonic, account.Seed)
		require.Len(t, strings.Fields(account.Seed), 24)
		require.Equal(t, testWalletPassword, account.WalletPassword)
		require.Len(t, account.WalletPassword, 64)
		_, err := hex.DecodeString(account.WalletPassword)
		require.NoError(t, err)
	}
}

func TestActivateAlreadyConfigured(t *testing.T) {
	lightning := newTestLightning(t, nil)
	lightning.getKeystore = testKeystore

	require.NoError(t, lightning.Activate())
	require.ErrorContains(t, lightning.Activate(), "already configured")
}

func TestActivateSealsSecretsWithSingleKey(t *testing.T) {
	env := &testEnvironment{canEncrypt: true}
	lightning := newTestLightning(t, env)
	lightning.getKeystore = testKeystore

	require.NoError(t, lightning.Activate())

	account := lightning.Account()
	require.NotNil(t, account)
	require.True(t, strings.HasPrefix(account.Seed, encryptedSecretV1Prefix))
	require.True(t, strings.HasPrefix(account.WalletPassword, encryptedSecretV1Prefix))
	// One key per account, stored once and reused for both secrets.
	require.Len(t, env.keys, 1)
	require.Contains(t, env.keys, "v0-deadbeef-ln-0")
}

func TestCredentials(t *testing.T) {
	env := &testEnvironment{canEncrypt: true}
	lightning := newTestLightning(t, env)
	lightning.getKeystore = testKeystore

	require.NoError(t, lightning.Activate())

	credentials, err := lightning.Credentials()
	require.NoError(t, err)
	require.Equal(t, testMnemonic, credentials.Mnemonic)
	require.Equal(t, testWalletPassword, credentials.Password)
	require.Equal(t, "signet", credentials.Network)
}

func TestCredentialsWithoutAccount(t *testing.T) {
	lightning := newTestLightning(t, nil)

	credentials, err := lightning.Credentials()
	require.Nil(t, credentials)
	require.Error(t, err)
}

func TestCredentialsWithoutWalletPassword(t *testing.T) {
	lightning := newTestLightning(t, nil)
	require.NoError(t, lightning.SetAccount(&config.LightningAccountConfig{
		Seed:            "test mnemonic",
		RootFingerprint: []byte{0xde, 0xad, 0xbe, 0xef},
		Code:            "v0-deadbeef-ln-0",
		Number:          0,
	}))

	credentials, err := lightning.Credentials()
	require.Nil(t, credentials)
	require.ErrorContains(t, err, "no wallet password")
}

func TestSealAndUnsealSecretsEncrypted(t *testing.T) {
	env := &testEnvironment{canEncrypt: true}
	lightning := newTestLightning(t, env)

	sealedMnemonic, sealedPassword, err := lightning.sealSecrets("v0-deadbeef-ln-0", "test mnemonic", "test password")
	require.NoError(t, err)
	require.NotEqual(t, "test mnemonic", sealedMnemonic)
	require.NotEqual(t, "test password", sealedPassword)
	require.True(t, strings.HasPrefix(sealedMnemonic, encryptedSecretV1Prefix))
	require.True(t, strings.HasPrefix(sealedPassword, encryptedSecretV1Prefix))
	require.Len(t, env.keys, 1)

	account := &config.LightningAccountConfig{
		Code:           "v0-deadbeef-ln-0",
		Seed:           sealedMnemonic,
		WalletPassword: sealedPassword,
	}

	mnemonic, err := lightning.unsealSecret(account, account.Seed)
	require.NoError(t, err)
	require.Equal(t, "test mnemonic", mnemonic)
	require.Equal(t, 1, env.loadCalls)

	password, err := lightning.unsealSecret(account, account.WalletPassword)
	require.NoError(t, err)
	require.Equal(t, "test password", password)
	require.Equal(t, 2, env.loadCalls)
}

func TestUnsealSecretUnsupportedFormat(t *testing.T) {
	env := &testEnvironment{
		canEncrypt: true,
		keys: map[string]string{
			"v0-deadbeef-ln-0": base64.StdEncoding.EncodeToString(make([]byte, 32)),
		},
	}
	lightning := newTestLightning(t, env)

	secret, err := lightning.unsealSecret(&config.LightningAccountConfig{
		Code: "v0-deadbeef-ln-0",
	}, "unversioned")
	require.Empty(t, secret)
	require.ErrorContains(t, err, "unsupported encrypted secret format")
}

func TestServiceStatus(t *testing.T) {
	lightning := newTestLightning(t, nil)

	// No wallet state pushed yet.
	require.Equal(t, &ServiceStatus{Status: "unknown"}, lightning.ServiceStatus())

	lightning.SetState(&walletState{Ready: true, ServerConnected: true})
	require.Equal(t, &ServiceStatus{Status: "operational"}, lightning.ServiceStatus())

	lightning.SetState(&walletState{Ready: true, ServerConnected: false})
	require.Equal(t, &ServiceStatus{Status: "major"}, lightning.ServiceStatus())
}

func TestSetStateNotifications(t *testing.T) {
	lightning := newTestLightning(t, nil)
	require.NoError(t, lightning.SetAccount(&config.LightningAccountConfig{
		Seed:            "test mnemonic",
		RootFingerprint: []byte{0xde, 0xad, 0xbe, 0xef},
		Code:            "v0-deadbeef-ln-0",
		Number:          0,
	}))

	var events []observable.Event
	unobserve := lightning.Observe(func(event observable.Event) {
		events = append(events, event)
	})
	defer unobserve()

	subjects := func() []string {
		result := []string{}
		for _, event := range events {
			result = append(result, event.Subject)
		}
		return result
	}

	// First push: readiness flips to true and the payment list is loaded.
	lightning.SetState(&walletState{Ready: true, BalanceSat: 100})
	require.Equal(t, []string{"lightning/ready", "lightning/list-payments"}, subjects())
	require.Equal(t, true, events[0].Object)

	// Identical push: no notifications.
	events = nil
	lightning.SetState(&walletState{Ready: true, BalanceSat: 100})
	require.Empty(t, events)

	// Balance change: only the payment list reloads.
	events = nil
	lightning.SetState(&walletState{Ready: true, BalanceSat: 200})
	require.Equal(t, []string{"lightning/list-payments"}, subjects())

	// New payment: only the payment list reloads.
	events = nil
	lightning.SetState(&walletState{Ready: true, BalanceSat: 200, Payments: []walletPayment{
		{ID: "payment-id", Kind: paymentKindReceive, Status: paymentStatusPending, AmountSat: 100},
	}})
	require.Equal(t, []string{"lightning/list-payments"}, subjects())

	// Readiness lost: only the ready event is emitted.
	events = nil
	lightning.SetState(&walletState{Ready: false, BalanceSat: 200, Payments: []walletPayment{
		{ID: "payment-id", Kind: paymentKindReceive, Status: paymentStatusPending, AmountSat: 100},
	}})
	require.Equal(t, []string{"lightning/ready"}, subjects())
	require.Equal(t, false, events[0].Object)
}

func TestDeactivate(t *testing.T) {
	env := &testEnvironment{canEncrypt: true}
	lightning := newTestLightning(t, env)
	lightning.getKeystore = testKeystore

	require.NoError(t, lightning.Activate())
	lightning.SetState(&walletState{Ready: true, ServerConnected: true})
	require.True(t, lightning.Ready())

	require.NoError(t, lightning.Deactivate())
	require.Nil(t, lightning.Account())
	require.False(t, lightning.Ready())
	// The state cache and the stored encryption key are cleared.
	require.Equal(t, &ServiceStatus{Status: "unknown"}, lightning.ServiceStatus())
	require.Empty(t, env.keys)

	// Deactivating without an account is a no-op.
	require.NoError(t, lightning.Deactivate())
}
