// SPDX-License-Identifier: Apache-2.0

package lightning

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"io"
	"reflect"
	"strings"
	"sync"

	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/accounts"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/accounts/types"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/coins/coin"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/config"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/keystore"
	"github.com/BitBoxSwiss/bitbox-wallet-app/backend/rates"
	"github.com/BitBoxSwiss/bitbox-wallet-app/util/errp"
	"github.com/BitBoxSwiss/bitbox-wallet-app/util/logging"
	"github.com/BitBoxSwiss/bitbox-wallet-app/util/observable"
	"github.com/BitBoxSwiss/bitbox-wallet-app/util/observable/action"
	"github.com/lightningnetwork/lnd/aezeed"
	"github.com/sirupsen/logrus"
	"golang.org/x/crypto/hkdf"
)

const (
	encryptedSecretV1Prefix = "v1:"
	// walletNetwork is the wavelength network the frontend wallet engine connects to.
	walletNetwork = "signet"
	// walletPasswordHKDFInfo is the HKDF info string used to derive the wallet database
	// password from the device entropy.
	walletPasswordHKDFInfo = "bitboxapp-wavelength-dbpw-v1"
	// aezeedSaltHKDFInfo is the HKDF info string used to derive the aezeed scrypt salt from
	// the device entropy. Deriving the salt (instead of using aezeed's default random
	// source) makes the 24-word mnemonic fully deterministic from the device entropy, so a
	// lost lightning.json can be regenerated by re-activating with the same device.
	aezeedSaltHKDFInfo = "bitboxapp-wavelength-aezeed-salt-v1"
)

// Keep this local to avoid importing backend.Environment and creating a package cycle.
type environment interface {
	CanEncryptLightningMnemonic() bool
	StoreLightningEncryptionKey(accountCode string, encryptionKey string) error
	LoadLightningEncryptionKey(accountCode string) (string, error)
	DeleteLightningEncryptionKey(accountCode string) error
}

// Lightning manages the lightning wallet credentials and mirrors the wallet state pushed by
// the frontend wavelength wallet engine.
type Lightning struct {
	observable.Implementation

	backendConfig *config.Config
	environment   environment
	getKeystore   func() keystore.Keystore

	log          *logrus.Entry
	ratesUpdater *rates.RateUpdater
	btcCoin      coin.Coin

	// state is the latest wallet state pushed by the frontend wallet engine, nil until the
	// first push.
	state     *walletState
	stateLock sync.RWMutex
}

// NewLightning creates a new instance of the Lightning struct.
func NewLightning(config *config.Config,
	environment environment,
	getKeystore func() keystore.Keystore,
	ratesUpdater *rates.RateUpdater,
	btcCoin coin.Coin) *Lightning {
	return &Lightning{
		backendConfig: config,
		environment:   environment,
		getKeystore:   getKeystore,
		log:           logging.Get().WithGroup("lightning"),
		ratesUpdater:  ratesUpdater,
		btcCoin:       btcCoin,
	}
}

// Activate derives the wallet credentials from the keystore entropy, seals them and persists
// the account configuration. The frontend reacts to the account change notification by booting
// the wavelength wallet engine with these credentials.
func (lightning *Lightning) Activate() error {
	if lightning.Account() != nil {
		return errp.New("Lightning accounts already configured")
	}

	// Drop any stale wallet state that slipped in around a previous deactivation, so the new
	// account cannot briefly serve the previous wallet's balance and payments.
	lightning.stateLock.Lock()
	lightning.state = nil
	lightning.stateLock.Unlock()

	keystore := lightning.getKeystore()
	if keystore == nil || !keystore.SupportsDeterministicEntropy() {
		return errp.New("No keystore available, or firmware out of date")
	}

	entropy, err := keystore.DeterministicEntropy()
	if err != nil {
		return err
	}

	fingerprint, err := keystore.RootFingerprint()
	if err != nil {
		return err
	}

	mnemonic, err := deriveMnemonic(entropy)
	if err != nil {
		lightning.log.WithError(err).Warn("Error generating mnemonic")
		return errp.New("Error generating mnemonic")
	}

	walletPassword, err := deriveWalletPassword(entropy)
	if err != nil {
		lightning.log.WithError(err).Warn("Error deriving wallet password")
		return errp.New("Error deriving wallet password")
	}

	accountCode := types.Code(strings.Join([]string{"v0-", hex.EncodeToString(fingerprint), "-ln-0"}, ""))
	sealedMnemonic, sealedPassword, err := lightning.sealSecrets(string(accountCode), mnemonic, walletPassword)
	if err != nil {
		lightning.log.WithError(err).Warn("Error configuring Lightning secure storage")
		return errp.New("Could not configure Lightning secure storage on this device")
	}

	lightningAccount := config.LightningAccountConfig{
		Seed:            sealedMnemonic,
		WalletPassword:  sealedPassword,
		RootFingerprint: fingerprint,
		Code:            accountCode,
		Number:          0,
	}
	if err = lightning.SetAccount(&lightningAccount); err != nil {
		if lightning.environment.CanEncryptLightningMnemonic() {
			if deleteErr := lightning.environment.DeleteLightningEncryptionKey(string(accountCode)); deleteErr != nil {
				lightning.log.WithError(deleteErr).Warn("Error deleting lightning encryption key after activation failure")
			}
		}
		return err
	}

	return nil
}

// deriveMnemonic encodes the device entropy as an aezeed mnemonic, the seed format of the
// wavelength wallet engine. The internal version 0, the Bitcoin genesis date as birthday and
// an entropy-derived scrypt salt make the resulting 24 words fully deterministic from the
// device entropy.
func deriveMnemonic(entropy []byte) (string, error) {
	if len(entropy) != aezeed.EntropySize {
		return "", errp.Newf("expected %d bytes of entropy, got %d", aezeed.EntropySize, len(entropy))
	}
	var seedEntropy [aezeed.EntropySize]byte
	copy(seedEntropy[:], entropy)
	saltSource := hkdf.New(sha256.New, entropy, nil, []byte(aezeedSaltHKDFInfo))
	cipherSeed, err := aezeed.New(0, &seedEntropy, aezeed.BitcoinGenesisDate,
		aezeed.WithRandomnessSource(saltSource))
	if err != nil {
		return "", err
	}
	mnemonic, err := cipherSeed.ToMnemonic(nil)
	if err != nil {
		return "", err
	}
	return strings.Join(mnemonic[:], " "), nil
}

// deriveWalletPassword derives the wallet database password from the device entropy.
func deriveWalletPassword(entropy []byte) (string, error) {
	password := make([]byte, 32)
	if _, err := io.ReadFull(
		hkdf.New(sha256.New, entropy, nil, []byte(walletPasswordHKDFInfo)),
		password,
	); err != nil {
		return "", err
	}
	return hex.EncodeToString(password), nil
}

// Deactivate clears the cached wallet state and removes the account configuration and its
// encryption key. The frontend reacts to the account change notification by disposing the
// wallet engine and wiping its local storage.
func (lightning *Lightning) Deactivate() error {
	account := lightning.Account()

	if account == nil {
		return nil
	}

	lightning.stateLock.Lock()
	lightning.state = nil
	lightning.stateLock.Unlock()

	if err := lightning.SetAccount(nil); err != nil {
		return err
	}

	if lightning.environment.CanEncryptLightningMnemonic() {
		if err := lightning.environment.DeleteLightningEncryptionKey(string(account.Code)); err != nil {
			lightning.log.WithError(err).Warn("Error deleting lightning encryption key")
		}
	}

	return nil
}

// readyState returns the last pushed wallet state, or an error if the account is not
// configured or the wallet engine has not reported a ready wallet yet.
func (lightning *Lightning) readyState() (*walletState, error) {
	if lightning.Account() == nil {
		return nil, errp.New("Lightning not initialized")
	}
	lightning.stateLock.RLock()
	defer lightning.stateLock.RUnlock()
	if lightning.state == nil || !lightning.state.Ready {
		return nil, errp.New("Lightning not initialized")
	}
	return lightning.state, nil
}

// CheckActive returns an error if the lightning service has not been activated.
func (lightning *Lightning) CheckActive() error {
	_, err := lightning.readyState()
	return err
}

// Ready returns true if the lightning account is configured and the frontend wallet engine
// reported a ready wallet state.
func (lightning *Lightning) Ready() bool {
	return lightning.CheckActive() == nil
}

func (lightning *Lightning) notifyReady() {
	lightning.Notify(observable.Event{
		Subject: "lightning/ready",
		Action:  action.Replace,
		Object:  lightning.Ready(),
	})
}

func (lightning *Lightning) notifyListPaymentsReload() {
	lightning.Notify(observable.Event{
		Subject: "lightning/list-payments",
		Action:  action.Reload,
	})
}

// SetState caches the wallet state pushed by the frontend wallet engine and notifies
// observers about readiness and payment list changes. Pushes are ignored while no account
// is configured (e.g. from an engine still shutting down after deactivation), so the cached
// state always belongs to the configured account.
func (lightning *Lightning) SetState(state *walletState) {
	if lightning.Account() == nil {
		lightning.log.Debug("Ignoring wallet state push without a configured account")
		return
	}
	lightning.stateLock.Lock()
	previous := lightning.state
	lightning.state = state
	lightning.stateLock.Unlock()

	previousReady := previous != nil && previous.Ready
	if state.Ready != previousReady {
		lightning.notifyReady()
	}
	if previous == nil || paymentsChanged(previous, state) {
		lightning.notifyListPaymentsReload()
	}
}

func paymentsChanged(previous *walletState, current *walletState) bool {
	return previous.BalanceSat != current.BalanceSat ||
		previous.PendingInSat != current.PendingInSat ||
		previous.PendingOutSat != current.PendingOutSat ||
		!reflect.DeepEqual(previous.Payments, current.Payments)
}

// Balance returns the balance of the lightning account from the last pushed wallet state.
func (lightning *Lightning) Balance() (*accounts.Balance, error) {
	state, err := lightning.readyState()
	if err != nil {
		return nil, err
	}
	return accounts.NewBalance(
		coin.NewAmountFromInt64(int64(state.BalanceSat)),
		coin.NewAmountFromInt64(int64(state.PendingInSat)),
	), nil
}

// ServiceStatus is the operational status of the lightning wallet service.
type ServiceStatus struct {
	// Status represents the current status.
	Status string `json:"status"`
}

// ServiceStatus derives the service status from the last pushed wallet state: "unknown" before
// the first push, "operational" while the wallet engine is connected to the wavelength server,
// "major" otherwise.
func (lightning *Lightning) ServiceStatus() *ServiceStatus {
	lightning.stateLock.RLock()
	defer lightning.stateLock.RUnlock()
	switch {
	case lightning.state == nil:
		return &ServiceStatus{Status: "unknown"}
	case lightning.state.ServerConnected:
		return &ServiceStatus{Status: "operational"}
	default:
		return &ServiceStatus{Status: "major"}
	}
}

// credentials are the unsealed wallet credentials handed to the frontend wallet engine.
type credentials struct {
	Mnemonic string `json:"mnemonic"`
	Password string `json:"password"`
	Network  string `json:"network"`
	// Code is the account code; the frontend uses it to namespace the locally persisted
	// wallet data per account.
	Code types.Code `json:"code"`
}

// Credentials unseals and returns the wallet credentials of the configured account.
func (lightning *Lightning) Credentials() (*credentials, error) {
	account := lightning.Account()
	if account == nil {
		return nil, errp.New("Lightning not initialized")
	}

	mnemonic, err := lightning.unsealSecret(account, account.Seed)
	if err != nil {
		lightning.log.WithError(err).Warn("Error unlocking Lightning mnemonic")
		return nil, errp.New("Error unlocking Lightning mnemonic from the device")
	}

	if account.WalletPassword == "" {
		return nil, errp.New("Lightning account has no wallet password; deactivate and activate again")
	}
	password, err := lightning.unsealSecret(account, account.WalletPassword)
	if err != nil {
		lightning.log.WithError(err).Warn("Error unlocking Lightning wallet password")
		return nil, errp.New("Error unlocking Lightning wallet password from the device")
	}

	return &credentials{
		Mnemonic: mnemonic,
		Password: password,
		Network:  walletNetwork,
		Code:     account.Code,
	}, nil
}

// sealSecrets encrypts the mnemonic and wallet password with a fresh encryption key that is
// handed to the platform for storage: one key per account, stored once and reused for both
// secrets. If the platform cannot store encryption keys, the secrets are persisted in
// plaintext.
func (lightning *Lightning) sealSecrets(
	accountCode string,
	mnemonic string,
	walletPassword string,
) (string, string, error) {
	if !lightning.environment.CanEncryptLightningMnemonic() {
		return mnemonic, walletPassword, nil
	}

	encryptionKey := make([]byte, 32)
	if _, err := io.ReadFull(rand.Reader, encryptionKey); err != nil {
		return "", "", err
	}

	sealedMnemonic, err := encryptSecret(mnemonic, encryptionKey)
	if err != nil {
		return "", "", err
	}

	sealedPassword, err := encryptSecret(walletPassword, encryptionKey)
	if err != nil {
		return "", "", err
	}

	if err := lightning.environment.StoreLightningEncryptionKey(
		accountCode,
		base64.StdEncoding.EncodeToString(encryptionKey),
	); err != nil {
		return "", "", err
	}

	return sealedMnemonic, sealedPassword, nil
}

// unsealSecret decrypts a sealed secret of the account with the stored encryption key. If the
// platform cannot store encryption keys, the secret is returned as-is.
func (lightning *Lightning) unsealSecret(
	account *config.LightningAccountConfig,
	sealedSecret string,
) (string, error) {
	if !lightning.environment.CanEncryptLightningMnemonic() {
		return sealedSecret, nil
	}

	encryptionKeyBase64, err := lightning.environment.LoadLightningEncryptionKey(string(account.Code))
	if err != nil {
		return "", err
	}

	encryptionKey, err := base64.StdEncoding.DecodeString(encryptionKeyBase64)
	if err != nil {
		return "", err
	}

	secret, err := decryptSecret(sealedSecret, encryptionKey)
	if err != nil {
		return "", err
	}

	return secret, nil
}

func encryptSecret(secret string, encryptionKey []byte) (string, error) {
	block, err := aes.NewCipher(encryptionKey)
	if err != nil {
		return "", err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", err
	}
	ciphertext := gcm.Seal(nil, nonce, []byte(secret), nil)
	return encryptedSecretV1Prefix + base64.StdEncoding.EncodeToString(append(nonce, ciphertext...)), nil
}

func decryptSecret(sealedSecret string, encryptionKey []byte) (string, error) {
	encodedCiphertext, ok := strings.CutPrefix(sealedSecret, encryptedSecretV1Prefix)
	if !ok {
		return "", errp.New("unsupported encrypted secret format")
	}
	rawCiphertext, err := base64.StdEncoding.DecodeString(encodedCiphertext)
	if err != nil {
		return "", err
	}
	block, err := aes.NewCipher(encryptionKey)
	if err != nil {
		return "", err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}
	if len(rawCiphertext) < gcm.NonceSize() {
		return "", errp.New("ciphertext too short")
	}
	nonce := rawCiphertext[:gcm.NonceSize()]
	ciphertext := rawCiphertext[gcm.NonceSize():]
	plaintext, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return "", err
	}
	return string(plaintext), nil
}

// Account returns the active lightning account, if any.
func (lightning *Lightning) Account() *config.LightningAccountConfig {
	lightningConfig := lightning.backendConfig.LightningConfig()
	if len(lightningConfig.Accounts) == 0 {
		return nil
	}
	// The config keeps a slice for forward compatibility with future multi-account support,
	// but the current backend only exposes and operates on the first configured account.
	return lightningConfig.Accounts[0]
}

// SetAccount updates the active lightning account and notifies about the config change.
func (lightning *Lightning) SetAccount(account *config.LightningAccountConfig) error {
	if err := lightning.backendConfig.ModifyLightningConfig(func(cfg *config.LightningConfig) error {
		cfg.Accounts = []*config.LightningAccountConfig{}
		if account != nil {
			accountCopy := *account
			cfg.Accounts = []*config.LightningAccountConfig{&accountCopy}
		}
		return nil
	}); err != nil {
		lightning.log.WithError(err).Warn("Error updating lightning config")
		return errp.New("Error updating lightning config")
	}

	lightning.Notify(observable.Event{
		Subject: "lightning/account",
		Action:  action.Reload,
	})
	lightning.notifyReady()

	return nil
}
